version: 2
jobs:
  build:
    working_directory: ~/gogobackend
    docker:
      - image: python:3.3.6
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: py.test

    