version: 2
jobs:
  build:
    working_directory: ~/gogobackend
    docker:
      - image: python:3.6.1
    steps:
      - checkout
      - run: pip3 install -r requirements.txt
      - run: pytest

    